In [ ]:
"Hello World"

In [1]:
greeting = "Hello World" #this is a string variable (<- this is a comment)

In [2]:
greeting

'Hello World'

In [3]:
greeting = "Hello World"

In [4]:
greeting

'Hello World'

In [5]:
print(greeting)

Hello World


# Basic Math

In [6]:
a=2
b=15

Getting the sum

In [7]:
a+b

17

In [8]:
my_sum = a+b #get the sum of a & b

In [9]:
#print the sum
my_sum

17

In [10]:
#Get the product
my_product = a * b
my_product

30

# Import Libraries

In [11]:
import numpy as np

In [12]:
#Define the numpy array
ages_list = [25,30,35,40,45]
#this is a Python List

In [13]:
ages = np.array(ages_list)
#this is a numpy array

In [14]:
ages

array([25, 30, 35, 40, 45])

In [15]:
#you can also do this in a single line
ages = np.array([25,30,35,40,45,50,55])
ages

array([25, 30, 35, 40, 45, 50, 55])

In [16]:
#Get the specific elements - note that in Python, the index starts from 0

In [17]:
ages[0]

25

In [18]:
ages[6]

55

In [19]:
ages[-1] #this is the las element

55

In [20]:
ages[0:4]
#goes from index = 0 to 3 (first 4 elements)

array([25, 30, 35, 40])

In [21]:
ages[:4]
#goes from beginning to index 3 (same result as above)

array([25, 30, 35, 40])

In [22]:
ages[1:4]
# goes from index = 1 to 3 (2nd to 4th elements)

array([30, 35, 40])

In [23]:
ages[1:]
# goes from index = 1 to last element (same result as above)

array([30, 35, 40, 45, 50, 55])

In [24]:
ages[:]
#goes from first to last element (same as ages)

array([25, 30, 35, 40, 45, 50, 55])

In [25]:
ages{::2}
#keeps every 2nd element only

SyntaxError: invalid syntax (<ipython-input-25-2c6111931db4>, line 1)

In [ ]:
ages[::-1]
#reverses order of elements